### ISSUE TITLE
ARC Directory Confusion

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/ReactionMechanismSimulator.jl#101]
I keep getting errors for every TS like the below. ARC seems to expect the TS files to be in the Species directory, but it puts them in the separate TSs directory. So far copying over the folders from the TSs directory to the Species folder every time this happens seems to get around this. 
```
Traceback (most recent call last):
  File "/Users/mattjohnson/RMGCODE/ARC/arc/job/ssh.py", line 196, in download_file
    localpath=local_file_path)
  File "/opt/anaconda3/envs/arc_env/lib/python3.7/site-packages/paramiko/sftp_client.py", line 801, in get
    with open(localpath, "wb") as fl:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mattjohnson/RMGCODE/ARC/Projects/explorer2/calcs/Species/TS2/composite_a3412/output.out'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../ARC.py", line 69, in <module>
    main()
  File "../../ARC.py", line 65, in main
    arc_object.execute()
  File "/Users/mattjohnson/RMGCODE/ARC/arc/main.py", line 564, in execute
    fine_only=self.fine_only,
  File "/Users/mattjohnson/RMGCODE/ARC/arc/scheduler.py", line 461, in __init__
    self.schedule_jobs()
  File "/Users/mattjohnson/RMGCODE/ARC/arc/scheduler.py", line 555, in schedule_jobs
    successful_server_termination = self.end_job(job=job, label=label, job_name=job_name)
  File "/Users/mattjohnson/RMGCODE/ARC/arc/scheduler.py", line 836, in end_job
    job.determine_job_status()  # also downloads output file
  File "/Users/mattjohnson/RMGCODE/ARC/arc/job/job.py", line 1348, in determine_job_status
    self._check_job_ess_status()  # populates self.job_status[1], and downloads the output file
  File "/Users/mattjohnson/RMGCODE/ARC/arc/job/job.py", line 1442, in _check_job_ess_status
    self._download_output_file()  # also downloads the check file and orbital file if exist
  File "/Users/mattjohnson/RMGCODE/ARC/arc/job/job.py", line 1238, in _download_output_file
    ssh.download_file(remote_file_path=remote_file_path, local_file_path=self.local_path_to_output_file)
  File "/Users/mattjohnson/RMGCODE/ARC/arc/job/ssh.py", line 200, in download_file
    raise ServerError(f'Could not download file {remote_file_path} from {self.server}. ')
arc.exceptions.ServerError: Could not download file runs/ARC_Projects/explorer2/TS2/composite_a3412/input.log from c3ddb01. 
```

**Comment by mjohnson541** [comment]
wrong repo
